run:
  timeout: 3m

linters-settings:
  errcheck:
    check-type-assertions: true

  lll:
    line-length: 120

  cyclop:
    max-complexity: 30

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - staticcheck
    - typecheck
    - unused
    - ineffassign
    - errorlint
    - lll
    - cyclop
    - noctx
    - testifylint
    - sloglint
